services:
  - type: web
    name: expense-tracker-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
