# Exported from Render on 2026-04-19T11:31:10Z
version: "1"
services:
- type: web
  name: expense-tracker-1
  runtime: python
  repo: https://github.com/shubhamsigh01/expense-tracker
  plan: free
  envVars:
  - key: JWT_SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: Mongo_URI
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python app.py
  autoDeployTrigger: commit
  rootDir: ./backend
