import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline

TRAINING_DATA = [
    ("McDonalds burger and fries", "Food"),
    ("Groceries at Walmart", "Food"),
    ("Pizza delivery from Dominos", "Food"),
    ("Lunch at subway", "Food"),
    ("Coffee at Starbucks", "Food"),
    ("Dinner at fancy restaurant", "Food"),
    ("Snacks from convenience store", "Food"),
    ("Ice cream desert", "Food"),
    ("Breakfast bagel and juice", "Food"),
    ("Sushi takeout", "Food"),
    ("Weekly vegetables from market", "Food"),
    ("Fast food drive thru", "Food"),
    ("Baked goods and pastry", "Food"),
    ("Meal prep ingredients", "Food"),
    ("Tacos from food truck", "Food"),
    
    ("Uber ride to airport", "Transport"),
    ("Gas station fill up", "Transport"),
    ("Monthly subway pass", "Transport"),
    ("Train ticket to city", "Transport"),
    ("Bus fare", "Transport"),
    ("Lyft ride home", "Transport"),
    ("Parking garage fee", "Transport"),
    ("Toll road charge", "Transport"),
    ("Car maintenance and oil change", "Transport"),
    ("Flight to New York", "Transport"),
    ("Bicycle repair", "Transport"),
    ("Scooter rental", "Transport"),
    ("Taxi to hotel", "Transport"),
    ("Car wash", "Transport"),
    ("Metro card reload", "Transport"),

    ("New shoes from Nike", "Shopping"),
    ("Winter jacket", "Shopping"),
    ("Amazon purchase", "Shopping"),
    ("Laptop case", "Shopping"),
    ("Birthday gift", "Shopping"),
    ("Jeans and t-shirt", "Shopping"),
    ("Home decor items", "Shopping"),
    ("Sunglasses", "Shopping"),
    ("Books from bookstore", "Shopping"),
    ("Online shopping clothing", "Shopping"),
    ("Video game console", "Shopping"),
    ("Makeup and cosmetics", "Shopping"),
    ("Watch battery replacement", "Shopping"),
    ("Furniture for living room", "Shopping"),
    ("Headphones", "Shopping"),

    ("Pharmacy medication", "Health"),
    ("Doctor appointment copay", "Health"),
    ("Dental cleaning", "Health"),
    ("Vitamins and supplements", "Health"),
    ("Therapy session", "Health"),
    ("Eye exam glasses", "Health"),
    ("Gym membership", "Health"),
    ("First aid kit supplies", "Health"),
    ("Chiropractor visit", "Health"),
    ("Bandages and ointment", "Health"),
    ("Prescription refill", "Health"),
    ("Yoga class", "Health"),
    ("Hospital bill", "Health"),
    ("Health insurance premium", "Health"),
    ("Protein powder", "Health"),

    ("Movie theater tickets", "Entertainment"),
    ("Netflix subscription", "Entertainment"),
    ("Concert tickets", "Entertainment"),
    ("Spotify premium", "Entertainment"),
    ("Museum entry fee", "Entertainment"),
    ("Amusement park pass", "Entertainment"),
    ("Bowling night", "Entertainment"),
    ("Theater play entry", "Entertainment"),
    ("Video game purchase", "Entertainment"),
    ("Escape room activity", "Entertainment"),
    ("Art exhibition", "Entertainment"),
    ("Comedy club show", "Entertainment"),
    ("Music festival pass", "Entertainment"),
    ("Board game", "Entertainment"),
    ("Karaoke night", "Entertainment"),

    ("Electric bill utility", "Bills"),
    ("Water bill", "Bills"),
    ("Internet service provider", "Bills"),
    ("Heater and gas bill", "Bills"),
    ("Mobile phone plan", "Bills"),
    ("Trash collection fee", "Bills"),
    ("Home insurance", "Bills"),
    ("Rent payment", "Bills"),
    ("Mortgage payment", "Bills"),
    ("Sewer bill", "Bills"),
    ("Cable TV package", "Bills"),
    ("HOA fee", "Bills"),
    ("Property tax", "Bills"),
    ("Car insurance bill", "Bills"),
    ("Security system monthly", "Bills"),

    ("College tuition", "Education"),
    ("Textbooks for semester", "Education"),
    ("Online course on Udemy", "Education"),
    ("School supplies pens notebooks", "Education"),
    ("Library late fee", "Education"),
    ("Certification exam fee", "Education"),
    ("Tutoring session", "Education"),
    ("Language learning app", "Education"),
    ("Seminar registration", "Education"),
    ("Workshop materials", "Education"),
    ("Student loan payment", "Education"),
    ("Extracurricular club fee", "Education"),
    ("Educational software license", "Education"),
    ("Science lab fee", "Education"),
    ("Coding bootcamp", "Education"),

    ("Hotel booking", "Travel"),
    ("Airbnb stay vacation", "Travel"),
    ("Flight to London", "Travel"),
    ("Tour guide fee", "Travel"),
    ("Visa application fee", "Travel"),
    ("Travel insurance", "Travel"),
    ("Rental car for trip", "Travel"),
    ("Souvenirs at tourist shop", "Travel"),
    ("Cruise ship booking", "Travel"),
    ("Resort fee", "Travel"),
    ("Baggage fee airline", "Travel"),
    ("Sim card for abroad", "Travel"),
    ("Airport lounge access", "Travel"),
    ("Currency exchange fee", "Travel"),
    ("Train across country", "Travel")
]

df = pd.DataFrame(TRAINING_DATA, columns=['description', 'category'])
model = make_pipeline(TfidfVectorizer(), MultinomialNB())
model.fit(df['description'], df['category'])

def predict(description: str) -> str:
    """Predict the category of an expense based on its description."""
    if not description:
        return "Other"
    prediction = model.predict([description])
    return prediction[0]
